"""migration_name_file_product

Revision ID: a395c7925d72
Revises: 6e286e3021b2
Create Date: 2024-11-20 20:13:37.518233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a395c7925d72"
down_revision: Union[str, None] = "6e286e3021b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column("имя файла", sa.String(length=255), nullable=False),
    )
    op.drop_column("product", "путь к файлу")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "путь к файлу",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("product", "имя файла")
    # ### end Alembic commands ###
