"""migration_product_image

Revision ID: 49a17313750c
Revises: a395c7925d72
Create Date: 2024-11-25 16:49:59.079995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49a17313750c"
down_revision: Union[str, None] = "a395c7925d72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("картинка", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "картинка")
    # ### end Alembic commands ###
