"""migrration_product_fields_edit

Revision ID: 0e027c9311ec
Revises: 49a17313750c
Create Date: 2024-12-05 17:23:49.875262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e027c9311ec"
down_revision: Union[str, None] = "49a17313750c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "картинка",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "product",
        "название",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.alter_column(
        "product", "описание", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "product",
        "имя файла",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "имя файла",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "product", "описание", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "product",
        "название",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "product",
        "картинка",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    # ### end Alembic commands ###
