"""migration_category_product_user_init

Revision ID: 6e286e3021b2
Revises: 
Create Date: 2024-10-24 19:13:09.780865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e286e3021b2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("название", sa.String(length=200), nullable=False),
        sa.Column("активный", sa.Boolean(), nullable=False),
        sa.Column(
            "дата создания",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("дата обновления", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id чата", sa.Integer(), nullable=False),
        sa.Column("никнейм", sa.String(length=200), nullable=True),
        sa.Column("имя", sa.String(length=200), nullable=False),
        sa.Column("фамилия", sa.String(length=200), nullable=True),
        sa.Column(
            "дата создания",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("дата обновления", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("название", sa.String(length=200), nullable=False),
        sa.Column("описание", sa.Text(), nullable=False),
        sa.Column("цена", sa.Integer(), nullable=False),
        sa.Column("путь к файлу", sa.String(length=255), nullable=False),
        sa.Column("id категории", sa.Integer(), nullable=False),
        sa.Column("активный", sa.Boolean(), nullable=False),
        sa.Column(
            "дата создания",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("дата обновления", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["id категории"], ["category.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("user")
    op.drop_table("category")
    # ### end Alembic commands ###
