"""migrration unique settings title

Revision ID: 333e64bb3675
Revises: 0e027c9311ec
Create Date: 2025-01-21 21:02:37.673511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "333e64bb3675"
down_revision: Union[str, None] = "0e027c9311ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category", ["название"])
    op.create_unique_constraint(
        "unique_title_category", "product", ["название", "id категории"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_title_category", "product", type_="unique")
    op.drop_constraint(None, "category", type_="unique")
    # ### end Alembic commands ###
